/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dy_myaudioappliction_transcode_TranscodeUtil */

#ifndef _Included_com_dy_myaudioappliction_transcode_TranscodeUtil
#define _Included_com_dy_myaudioappliction_transcode_TranscodeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dy_myaudioappliction_transcode_TranscodeUtil
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dy_myaudioappliction_transcode_TranscodeUtil_convertmp3
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_dy_myaudioappliction_transcode_TranscodeUtil
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dy_myaudioappliction_transcode_TranscodeUtil_getLameVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
